# Setup
version_name: TaskDiffusion_vitL_nyud
out_dir: "."

# Database
train_db_name: NYUD
val_db_name: NYUD
trBatch: 2
valBatch: 6
nworkers: 20
ignore_index: 255
seed: 1919810

# Optimizer and scheduler
intermediate_supervision: False
val_interval: 4000
epochs: 999999
max_iter: 40000
optimizer: adam
optimizer_kwargs:
   lr: 0.00001
   weight_decay: 1.e-6
scheduler: poly
grad_clip_param: {'max_norm': 10, 'norm_type': 2}
ignore_invalid_area_depth: True

# Model
model: TaskDiffusion
backbone: TaskDiffusion_vitL
head: TaskDiffusion_head
final_embed_dim: 768
timesteps: 3
randsteps: 1
module_layer: 3
with_aux: True
aux_weight: 0.25
pseudo_start: 40000

# Tasks
task_dictionary:
   include_semseg: True
   include_depth: True
   include_edge: True
   include_normals: True
   edge_w: 0.90

# bits scale
bit_scales:
   all: 0.01

# Loss kwargs
loss_kwargs:
   loss_weights:
       semseg: 1.0
       depth: 1.0
       normals: 10
       edge: 50.0
       load_balancing: 0.0003
